name: scheduler

on:
  schedule:
    - cron: '* * * * *'

jobs:
  call-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Call netlify scheduler
        run: curl 'https://alertbase.netlify.app/.netlify/functions/scheduler'
