name: scheduler

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  call-scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Call netlify scheduler
        run: curl 'http://localhost:8888/.netlify/functions/scheduler'
